services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  web:
    build: ./web_app
    container_name: web
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    ports:
      - "5000:5000"
    restart: unless-stopped

  processor:
    build: ./processor
    container_name: processor
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    depends_on:
      - redis
      - db
    restart: unless-stopped

  reader:
    build: ./reader_app
    container_name: reader
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    depends_on:
      - db
    ports:
      - "5001:5000"
    restart: unless-stopped

  load_tester:
    build: ./load_tester
    environment:
      TARGET_URL: http://web:5000/like
      REQUEST_COUNT: 1000
    depends_on:
      - web

volumes:
  db_data:
